version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mongodb
    links:
      - mongodb
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
      MONGO_INITDB_DATABASE: "${MONGO_DB}"

secrets:
  mongodb_root_password:
    file: ./db_root_password
  mongodb_root_username:
    file: ./db_root_username